package com.baye.exemplecustomerservice.web;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-06-16T13:17:10.423Z
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://web.exemplecustomerservice.baye.com/", name = "CustomerSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerSoapService {

    @WebMethod
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://web.exemplecustomerservice.baye.com/", className = "com.baye.exemplecustomerservice.web.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://web.exemplecustomerservice.baye.com/", className = "com.baye.exemplecustomerservice.web.SaveCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.baye.exemplecustomerservice.web.Customer saveCustomer(

        @WebParam(name = "arg0", targetNamespace = "")
        com.baye.exemplecustomerservice.web.CustomerRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "customerById", targetNamespace = "http://web.exemplecustomerservice.baye.com/", className = "com.baye.exemplecustomerservice.web.CustomerById")
    @ResponseWrapper(localName = "customerByIdResponse", targetNamespace = "http://web.exemplecustomerservice.baye.com/", className = "com.baye.exemplecustomerservice.web.CustomerByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.baye.exemplecustomerservice.web.Customer customerById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "customerList", targetNamespace = "http://web.exemplecustomerservice.baye.com/", className = "com.baye.exemplecustomerservice.web.CustomerList")
    @ResponseWrapper(localName = "customerListResponse", targetNamespace = "http://web.exemplecustomerservice.baye.com/", className = "com.baye.exemplecustomerservice.web.CustomerListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.baye.exemplecustomerservice.web.Customer> customerList()
;
}
